### PR TITLE
feat: add support for DuelingDQN

### PR DESCRIPTION
**Pull request by retinfai**

### CODE REVIEW

**Comment by retinfai** [comment]
# Results
Tested with the following prompt:
```
python3 example_training_loop.py --task "CartPole-v1" --algorithm DoubleDQN
```
DuelingDQNParams

In comparison a DQN Benchmark:
DQN
Using the same prompt:
```
python3 example_training_loop.py --task "CartPole-v1" --algorithm DQN
```

# Notes
As you can see they converge around the 20000 step mark. However DQN a little before, and DuelingDQN a little after – also DQN is more stable in its learning. @dvalenciar am I missing something

**Comment by beardyFace** [comment]
Question - you tested using python3 example_training_loop.py --task "CartPole-v1" --algorithm DoubleDQN

Is this for double or dueling the code looks like dueling?

**Comment by retinfai** [comment]
Ahh yep, you're right. It's meant to say DuelingDQN. Fixed now

**Comment by beardyFace** [comment]
Performance-wise - DuelingDQN doesn't always outperform DQN, and there is likely a hyperparameter tweak that is required to get its performance "optimal" vs DQN. If David is happy with the actual implementation then I am happy with the code changes

**Review by beardyFace — APPROVED** [review]

**Pull request merged**
